# Generated by Django 6.0.3 on 2026-06-05 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0004_alter_workspace_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keycloak_sub', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('workspace_name', models.CharField(max_length=255)),
                ('secretaria', models.CharField(max_length=120)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('denied', 'Negado')], db_index=True, default='pending', max_length=20)),
                ('denial_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('previous_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='re_requests', to='access_requests.accessrequest')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_access_requests', to='workspaces.workspacemember')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'access_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
