# Generated by Django 6.0.3 on 2026-06-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
