# Generated by Django 5.1.4 on 2026-03-14 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('issue_assigned', 'Issue atribuída'), ('issue_commented', 'Comentário em issue'), ('issue_state_changed', 'Estado de issue alterado'), ('cpm_critical_alert', 'Alerta CPM crítico'), ('portfolio_rag_changed', 'RAG do portfolio alterado'), ('wiki_mentioned', 'Mencionado em wiki')], max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('title', models.CharField(max_length=500)),
                ('message', models.TextField(blank=True, null=True)),
                ('action_url', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='workspaces.workspacemember')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspaces.workspacemember')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
