# Generated by Django 5.1.4 on 2026-06-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_merge_0002_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('issue_assigned', 'Issue atribuída'), ('issue_commented', 'Comentário em issue'), ('issue_state_changed', 'Estado de issue alterado'), ('cpm_critical_alert', 'Alerta CPM crítico'), ('portfolio_rag_changed', 'RAG do portfolio alterado'), ('wiki_mentioned', 'Mencionado em wiki'), ('issue_mentioned', 'Mencionado em issue'), ('issue_updated', 'Issue atualizada (watcher)'), ('wiki_updated', 'Página wiki atualizada (watcher)'), ('access_request', 'Solicitação de acesso')], max_length=50),
        ),
    ]
