# Generated by Django 5.1.4 on 2026-03-14 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.JSONField(blank=True, null=True)),
                ('emoji', models.CharField(blank=True, max_length=10, null=True)),
                ('cover_url', models.TextField(blank=True, null=True)),
                ('sort_order', models.FloatField(db_column='position', default=65535.0)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('published_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='created_wiki_pages', to='workspaces.workspacemember')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='wiki.wikipage')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_wiki_pages', to='workspaces.workspacemember')),
            ],
            options={
                'db_table': 'wiki_pages',
                'ordering': ['sort_order'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WikiPageComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('selection_text', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wiki_comments', to='workspaces.workspacemember')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wiki.wikipage')),
            ],
            options={
                'db_table': 'wiki_page_comments',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WikiPageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('content', models.JSONField()),
                ('change_summary', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspacemember')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='wiki.wikipage')),
            ],
            options={
                'db_table': 'wiki_page_versions',
                'ordering': ['-version_number'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WikiSpace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=10, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='created_wiki_spaces', to='workspaces.workspacemember')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiki_spaces', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_spaces', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'wiki_spaces',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='wikipage',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='wiki.wikispace'),
        ),
        migrations.CreateModel(
            name='WikiIssueLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(choices=[('spec', 'Especificação'), ('runbook', 'Runbook'), ('postmortem', 'Postmortem'), ('decision', 'Decisão'), ('related', 'Relacionado')], default='related', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspacemember')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_links', to='issues.issue')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_links', to='wiki.wikipage')),
            ],
            options={
                'db_table': 'wiki_issue_links',
                'managed': True,
                'unique_together': {('page', 'issue')},
            },
        ),
    ]
