# Generated by Django 5.1.4 on 2026-06-05 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_add_wiki_watchers_and_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikiactivity',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='wikipagewatcher',
            options={'managed': True},
        ),
    ]
