# Generated by Django 5.1.4 on 2026-06-12 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0004_add_issue_watchers'),
        ('projects', '0002_project_dates'),
        ('workspaces', '0004_accessrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Nova'), ('reviewing', 'Em análise'), ('planned', 'Planejada'), ('building', 'Em execução'), ('shipped', 'Entregue'), ('parked', 'Estacionada')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ideas', to='workspaces.workspacemember')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_ideas', to='workspaces.workspacemember')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas', to='projects.project')),
                ('promoted_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_ideas', to='issues.issue')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='workspaces.workspace')),
            ],
        ),
    ]
