# Generated by Django 5.1.4 on 2026-06-12 00:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdeaFieldDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("key", models.SlugField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("number", "Número"),
                            ("select", "Seleção"),
                            ("multi_select", "Múltipla seleção"),
                            ("date", "Data"),
                            ("user", "Usuário"),
                        ],
                        max_length=20,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("ordering", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idea_field_definitions",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "label"],
                "unique_together": {("workspace", "key")},
            },
        ),
        migrations.CreateModel(
            name="IdeaFieldValue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("text_value", models.TextField(blank=True, null=True)),
                ("number_value", models.FloatField(blank=True, null=True)),
                ("date_value", models.DateField(blank=True, null=True)),
                ("json_value", models.JSONField(blank=True, null=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="discovery.ideafielddefinition",
                    ),
                ),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_values",
                        to="discovery.idea",
                    ),
                ),
                (
                    "user_value",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idea_field_values",
                        to="workspaces.workspacemember",
                    ),
                ),
            ],
            options={
                "unique_together": {("idea", "field")},
            },
        ),
    ]
