# Generated by Django 5.1.4 on 2026-06-12 00:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0002_ideafielddefinition_ideafieldvalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdeaView",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "view_type",
                    models.CharField(
                        choices=[
                            ("table", "Tabela"),
                            ("board", "Quadro"),
                            ("roadmap", "Roadmap"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("visible_columns", models.JSONField(blank=True, default=list)),
                ("group_by", models.CharField(blank=True, max_length=100, null=True)),
                ("ordering", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="idea_views",
                        to="workspaces.workspacemember",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idea_views",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
