# Generated by Django 5.1.4 on 2026-06-13 00:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_ideaview'),
        ('workspaces', '0005_merge_20260612_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('note', 'Nota'), ('link', 'Link'), ('feedback', 'Feedback')], default='note', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_insights', to='workspaces.workspacemember')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='discovery.idea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.FloatField(default=0)),
                ('effort', models.FloatField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('reach', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard', to='discovery.idea')),
            ],
        ),
    ]
