# Generated by Django 5.1.4 on 2026-03-14 01:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_portfolios', to='workspaces.workspacemember')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'portfolios',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PortfolioObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='portfolio.portfolio')),
            ],
            options={
                'db_table': 'portfolio_objectives',
                'ordering': ['due_date', 'title'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget_planned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('budget_actual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('rag_status', models.CharField(choices=[('GREEN', 'Verde'), ('AMBER', 'Amarelo'), ('RED', 'Vermelho')], default='GREEN', max_length=10)),
                ('rag_override', models.BooleanField(default=False)),
                ('rag_note', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_projects', to='portfolio.portfolio')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to='projects.project')),
            ],
            options={
                'db_table': 'portfolio_projects',
                'ordering': ['project__name'],
                'managed': True,
                'unique_together': {('portfolio', 'project')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioCostEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='entry_date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(choices=[('labor', 'Mão de obra'), ('infrastructure', 'Infraestrutura'), ('licenses', 'Licenças'), ('services', 'Serviços'), ('other', 'Outros')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='registered_by', null=True, on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspacemember')),
                ('portfolio_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_entries', to='portfolio.portfolioproject')),
            ],
            options={
                'db_table': 'portfolio_cost_entries',
                'ordering': ['-date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PortfolioProjectDep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_deps', to='portfolio.portfolioproject')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_deps', to='portfolio.portfolioproject')),
            ],
            options={
                'db_table': 'portfolio_project_deps',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ObjectiveProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_links', to='projects.project')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_projects', to='portfolio.portfolioobjective')),
            ],
            options={
                'db_table': 'objective_projects',
                'managed': True,
                'unique_together': {('objective', 'project')},
            },
        ),
    ]
