# Generated by Django 5.1.4 on 2026-04-23 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycles', '0001_initial'),
        ('issues', '0003_add_issue_color'),
        ('workspaces', '0002_alter_workspacemember_keycloak_sub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied')], default='draft', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, db_column='applied_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_sprint_plans', to='workspaces.workspacemember')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='created_sprint_plans', to='workspaces.workspacemember')),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_plan', to='cycles.cycle')),
            ],
            options={
                'db_table': 'sprint_plans',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SprintPlanAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('planned_days', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('planned_story_points', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_plan_allocations', to='issues.issue')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='cycles.sprintplan')),
                ('planned_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_plan_allocations', to='workspaces.workspacemember')),
            ],
            options={
                'db_table': 'sprint_plan_allocations',
                'ordering': ['rank', 'created_at'],
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('planned_days__isnull', True), ('planned_days__gte', 0), _connector='OR'), name='sprint_plan_allocation_planned_days_non_negative'), models.CheckConstraint(condition=models.Q(('planned_story_points__isnull', True), ('planned_story_points__gte', 0), _connector='OR'), name='sprint_plan_allocation_story_points_non_negative')],
                'unique_together': {('plan', 'issue')},
            },
        ),
        migrations.CreateModel(
            name='SprintPlanMemberCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_days', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('override_days', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_plan_capacities', to='workspaces.workspacemember')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_capacities', to='cycles.sprintplan')),
            ],
            options={
                'db_table': 'sprint_plan_member_capacities',
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('default_days__gte', 0)), name='sprint_plan_member_capacity_default_days_non_negative'), models.CheckConstraint(condition=models.Q(('override_days__isnull', True), ('override_days__gte', 0), _connector='OR'), name='sprint_plan_member_capacity_override_days_non_negative')],
                'unique_together': {('plan', 'member')},
            },
        ),
    ]
