# Generated by Django 5.1.4 on 2026-03-14 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('milestones', '0001_initial'),
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.JSONField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('urgent', 'Urgente'), ('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa'), ('none', 'Nenhuma')], default='none', max_length=10)),
                ('type', models.CharField(choices=[('task', 'Tarefa'), ('bug', 'Bug'), ('story', 'História'), ('epic', 'Épico'), ('subtask', 'Sub-tarefa')], default='task', max_length=10)),
                ('estimate_points', models.IntegerField(blank=True, null=True)),
                ('size', models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL')], max_length=5, null=True)),
                ('estimate_days', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.FloatField(default=65535.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to='workspaces.workspacemember')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='created_issues', to='workspaces.workspacemember')),
                ('epic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epic_issues', to='issues.issue')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='milestones.milestone')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_issues', to='issues.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_issues', to='workspaces.workspacemember')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='projects.issuestate')),
            ],
            options={
                'db_table': 'issues',
                'ordering': ['sort_order'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IssueActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(db_column='activity_type', max_length=50)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('old_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('new_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_activities', to='workspaces.workspacemember')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='issues.issue')),
            ],
            options={
                'db_table': 'issue_activities',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IssueAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(db_column='file_name', max_length=255)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('storage_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issues.issue')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspacemember')),
            ],
            options={
                'db_table': 'issue_attachments',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField()),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_comments', to='workspaces.workspacemember')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue')),
            ],
            options={
                'db_table': 'issue_comments',
                'ordering': ['created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IssueLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.issue')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.label')),
            ],
            options={
                'db_table': 'issue_labels',
                'managed': True,
                'unique_together': {('issue', 'label')},
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='issues', through='issues.IssueLabel', to='projects.label'),
        ),
        migrations.CreateModel(
            name='IssueRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('blocks', 'Bloqueia'), ('blocked_by', 'Bloqueado por'), ('duplicates', 'Duplica'), ('duplicate_of', 'Duplicata de'), ('relates_to', 'Relacionado a'), ('finish_to_start', 'Termina para iniciar'), ('start_to_start', 'Inicia para iniciar'), ('finish_to_finish', 'Termina para terminar'), ('start_to_finish', 'Inicia para terminar')], max_length=30)),
                ('lag_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='issues.issue')),
                ('related_issue', models.ForeignKey(db_column='related_id', on_delete=django.db.models.deletion.CASCADE, related_name='reverse_relations', to='issues.issue')),
            ],
            options={
                'db_table': 'issue_relations',
                'managed': True,
                'unique_together': {('issue', 'related_issue', 'relation_type')},
            },
        ),
    ]
