# Generated by Django 6.0.3 on 2026-03-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DROP FUNCTION IF EXISTS next_sequence_id(UUID);
            CREATE FUNCTION next_sequence_id(project_uuid UUID)
            RETURNS INTEGER AS $$
            DECLARE
              next_id INTEGER;
            BEGIN
              SELECT COALESCE(MAX(sequence_id), 0) + 1
              INTO next_id
              FROM issues
              WHERE project_id = project_uuid;

              RETURN next_id;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS next_sequence_id(UUID);"
        ),
    ]
