# Generated by Django 5.1.4 on 2026-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_create_next_sequence_id_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
