# Generated by Django 5.1.4 on 2026-06-05 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_add_issue_watchers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuewatcher',
            options={'managed': True},
        ),
    ]
