# Generated by Django 5.1.4 on 2026-06-14 00:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_alter_issuewatcher_options'),
        ('workspaces', '0005_merge_20260612_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('title_template', models.CharField(max_length=500)),
                ('description', models.JSONField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('urgent', 'Urgente'), ('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa'), ('none', 'Nenhuma')], default='none', max_length=20)),
                ('size', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to='workspaces.workspacemember')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_templates', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'issue_templates',
                'ordering': ['name'],
                'managed': True,
            },
        ),
    ]
