# Generated by Django 5.1.4 on 2026-03-14 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpmIssueData',
            fields=[
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cpm_data', serialize=False, to='issues.issue')),
                ('duration_days', models.IntegerField(default=1)),
                ('es', models.IntegerField(blank=True, null=True)),
                ('ef', models.IntegerField(blank=True, null=True)),
                ('ls', models.IntegerField(blank=True, null=True)),
                ('lf', models.IntegerField(blank=True, null=True)),
                ('slack', models.IntegerField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cpm_issue_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CpmBaseline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, to='workspaces.workspacemember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpm_baselines', to='projects.project')),
            ],
            options={
                'db_table': 'cpm_baselines',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
