# Generated by Django 5.1.4 on 2026-03-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemember',
            name='keycloak_sub',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='workspacemember',
            unique_together={('workspace', 'keycloak_sub')},
        ),
    ]
