# Generated by Django 6.0.3 on 2026-06-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_personaltask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='workspacemember',
            options={'managed': False},
        ),
    ]
