# Generated by Django 5.1.4 on 2026-06-12 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_accessrequest'),
        ('workspaces', '0004_alter_workspace_options_and_more'),
    ]

    operations = [
    ]
