# Generated by Django 5.1.4 on 2026-03-14 13:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('technical', 'Técnico'), ('schedule', 'Prazo'), ('cost', 'Custo'), ('resource', 'Recurso'), ('external', 'Externo'), ('stakeholder', 'Stakeholder')], default='technical', max_length=50)),
                ('probability', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impact', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score', models.SmallIntegerField(editable=False)),
                ('status', models.CharField(choices=[('identified', 'Identificado'), ('analyzing', 'Em análise'), ('mitigating', 'Mitigando'), ('monitoring', 'Monitorando'), ('closed', 'Fechado'), ('accepted', 'Aceito'), ('occurred', 'Ocorreu')], default='identified', max_length=20)),
                ('response_type', models.CharField(blank=True, choices=[('avoid', 'Evitar'), ('transfer', 'Transferir'), ('mitigate', 'Mitigar'), ('accept', 'Aceitar')], max_length=20, null=True)),
                ('mitigation_plan', models.TextField(blank=True, null=True)),
                ('contingency_plan', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='created_risks', to='workspaces.workspacemember')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_risks', to='workspaces.workspacemember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
            ],
            options={
                'db_table': 'project_risks',
                'ordering': ['-score', 'title'],
                'managed': True,
            },
        ),
    ]
