# Generated by Django 5.1.4 on 2026-04-14 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0003_add_issue_color'),
        ('projects', '0001_initial'),
        ('workspaces', '0002_alter_workspacemember_keycloak_sub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='issues.issue')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='workspaces.workspacemember')),
            ],
            options={
                'db_table': 'time_entries',
                'ordering': ['-date', '-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemberCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('available_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('note', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='workspaces.workspacemember')),
            ],
            options={
                'db_table': 'member_capacities',
                'managed': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='member_capacity_month_1_12'), models.CheckConstraint(condition=models.Q(('available_days__gte', 0)), name='member_capacity_available_days_non_negative')],
                'unique_together': {('member', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ResourceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_rate_brl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_profiles', to='workspaces.workspacemember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_profiles', to='projects.project')),
            ],
            options={
                'db_table': 'resource_profiles',
                'managed': True,
                'unique_together': {('project', 'member')},
            },
        ),
    ]
